[serviceweaver]
binary = "./hello"

[single]
listeners.hello = {address = "localhost:8081"}

[multi]
listeners.hello = {address = "localhost:8081"}

[gke]
regions = ["us-west1"]
listeners.hello = {public_hostname = "hello.example.com"}