// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package cockroachdb

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"github.com/shijuvar/service-weaver/orderapp/model"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

var _ codegen.LatestVersion = codegen.Version[[0][17]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.17.0 (codegen
version v0.17.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/shijuvar/service-weaver/orderapp/cockroachdb/Repository",
		Iface: reflect.TypeOf((*Repository)(nil)).Elem(),
		Impl:  reflect.TypeOf(repository{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return repository_local_stub{impl: impl.(Repository), tracer: tracer, createOrderMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/shijuvar/service-weaver/orderapp/cockroachdb/Repository", Method: "CreateOrder", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return repository_client_stub{stub: stub, createOrderMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/shijuvar/service-weaver/orderapp/cockroachdb/Repository", Method: "CreateOrder", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return repository_server_stub{impl: impl.(Repository), addLoad: addLoad}
		},
		RefData: "",
	})
}

// weaver.Instance checks.
var _ weaver.InstanceOf[Repository] = (*repository)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*repository)(nil)

// Local stub implementations.

type repository_local_stub struct {
	impl               Repository
	tracer             trace.Tracer
	createOrderMetrics *codegen.MethodMetrics
}

// Check that repository_local_stub implements the Repository interface.
var _ Repository = (*repository_local_stub)(nil)

func (s repository_local_stub) CreateOrder(ctx context.Context, a0 model.Order) (err error) {
	// Update metrics.
	begin := s.createOrderMetrics.Begin()
	defer func() { s.createOrderMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "cockroachdb.Repository.CreateOrder", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.CreateOrder(ctx, a0)
}

// Client stub implementations.

type repository_client_stub struct {
	stub               codegen.Stub
	createOrderMetrics *codegen.MethodMetrics
}

// Check that repository_client_stub implements the Repository interface.
var _ Repository = (*repository_client_stub)(nil)

func (s repository_client_stub) CreateOrder(ctx context.Context, a0 model.Order) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.createOrderMetrics.Begin()
	defer func() { s.createOrderMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "cockroachdb.Repository.CreateOrder", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	(a0).WeaverMarshal(enc)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Server stub implementations.

type repository_server_stub struct {
	impl    Repository
	addLoad func(key uint64, load float64)
}

// Check that repository_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*repository_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s repository_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "CreateOrder":
		return s.createOrder
	default:
		return nil
	}
}

func (s repository_server_stub) createOrder(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 model.Order
	(&a0).WeaverUnmarshal(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.CreateOrder(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}
