//go:build !ignoreWeaverGen

package model

// Code generated by "weaver generate". DO NOT EDIT.
import (
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
)

var _ codegen.LatestVersion = codegen.Version[[0][11]struct{}]("You used 'weaver generate' codegen version 0.11.0, but you built your code with an incompatible weaver module version. Try upgrading 'weaver generate' and re-running it.")

// weaver.Instance checks.

// weaver.Router checks.

// Local stub implementations.

// Client stub implementations.

// Server stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Notification)(nil)

type __is_Notification[T ~struct {
	weaver.AutoMarshal
	OrderID    string
	CustomerID string
	Event      string
	Modes      []string
}] struct{}

var _ __is_Notification[Notification]

func (x *Notification) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Notification.WeaverMarshal: nil receiver"))
	}
	enc.String(x.OrderID)
	enc.String(x.CustomerID)
	enc.String(x.Event)
	serviceweaver_enc_slice_string_4af10117(enc, x.Modes)
}

func (x *Notification) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Notification.WeaverUnmarshal: nil receiver"))
	}
	x.OrderID = dec.String()
	x.CustomerID = dec.String()
	x.Event = dec.String()
	x.Modes = serviceweaver_dec_slice_string_4af10117(dec)
}

func serviceweaver_enc_slice_string_4af10117(enc *codegen.Encoder, arg []string) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.String(arg[i])
	}
}

func serviceweaver_dec_slice_string_4af10117(dec *codegen.Decoder) []string {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]string, n)
	for i := 0; i < n; i++ {
		res[i] = dec.String()
	}
	return res
}

var _ codegen.AutoMarshal = (*OrderPayment)(nil)

type __is_OrderPayment[T ~struct {
	weaver.AutoMarshal
	OrderID    string
	CustomerID string
	Amount     float64
}] struct{}

var _ __is_OrderPayment[OrderPayment]

func (x *OrderPayment) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("OrderPayment.WeaverMarshal: nil receiver"))
	}
	enc.String(x.OrderID)
	enc.String(x.CustomerID)
	enc.Float64(x.Amount)
}

func (x *OrderPayment) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("OrderPayment.WeaverUnmarshal: nil receiver"))
	}
	x.OrderID = dec.String()
	x.CustomerID = dec.String()
	x.Amount = dec.Float64()
}
