[serviceweaver]
binary = "./orderapp"
rollout = "5m"
colocate = [
    [
        "main",
        "github.com/shijuvar/service-weaver/orderapp/cockroachdb/Repository"
    ]
]

[single]
listeners.orderapi = {address = "localhost:3000"}

[multi]
listeners.orderapi = {address = "localhost:3000"}

[gke]
regions = ["us-west1"]
listeners.orderapi = {public_hostname = "orderapp.example.com"}

["github.com/shijuvar/service-weaver/orderapp/cockroachdb/Repository"]
Driver = "postgres"
Source = "postgresql://shijuvar@localhost:26257/ordersdb?sslmode=disable"